### ISSUE TITLE
SDG deleted his tileset and repostory.

### ISSUE THREAD

**Issue by Firestorm01X2** [4nonch/BN---Primitive-Launcher#11]
https://github.com/SomeDeadGuy/UndeadPeopleTilese does not exist anymore. Launcher should be reatargeted to alive fork.
Mine fork can be used:
https://github.com/Firestorm01X2/UndeadPeopleTileset

It was updated.

**Comment by 4nonch** [comment]
https://github.com/4nonch/BN---Primitive-Launcher/releases/tag/0.9.5-SDG-fix

**Comment by Firestorm01X2** [comment]
Thank you for quick fix!
