### ISSUE TITLE
Warning! Build names changed due migration to github actions.

### ISSUE THREAD

**Issue by Firestorm01X2** [4nonch/BN---Primitive-Launcher#8]
Warning! Build names changed due migration to github actions: https://github.com/cataclysmbnteam/Cataclysm-BN/releases
So launcher likely is not ging to pick it up without editing.

**Comment by 4nonch** [comment]
Forgot to close issue.
https://github.com/4nonch/BN---Primitive-Launcher/releases/tag/0%2C9%2C4f
