### ISSUE TITLE
DirectoryNotFoundException when updating UndeadPeopleTileset-master

### ISSUE THREAD

**Issue by WilliamElder** [4nonch/BN---Primitive-Launcher#9]
It seems like the UndeadPeopleTileset-master in the Bright Nights install directory is missing the TILESET_MODS folder, as it has been renamed to BN_TILESET_MODS instead.

I can't post the text of the stack trace, as the exception popup window does not allow copying.

**Comment by 4nonch** [comment]
Thanks for responce, will get a closer look. Sorry for a delay

**Comment by 4nonch** [comment]
I think it works now, check it https://github.com/4nonch/BN---Primitive-Launcher/releases/tag/0.9.5.

**Comment by WilliamElder** [comment]
It seems to be working fine now. Thank you!
